//
//  APIConstant.swift


import Foundation


let api_email = "email"

let api_device_type = "device_type"
let api_device_uuid = "device_uuid"
let api_social_type = "social_type"
let api_social_type_value = "fb"
let api_social_token = "social_token"
let api_is_social_login = "is_social_login"
let api_device = "ios"
let api_device_token = "device_token"
let api_appVersion = "appVersion"
let api_appversion = "appversion"
let api_firstname = "first_name"
let api_lastname = "last_name"
let api_mobile_number = "mobile_number"
let api_telephone = "telephone"
let api_apartment = "apartment"
let api_push_notification = "push_notification"
let api_credit_card = "credit_card"
let api_gender = "gender"
let api_full_name = "full_name"
let api_fullname = "fullname"
let api_customer_id = "customer_id"
let api_customerid = "customerid"

let api_store = "store"
let api_comment = "comment"
let api_comments = "comments"
let api_company = "company"
let api_location = "location"
let api_date = "date"
let api_time = "time"

let api_product_name = "productname"
let api_product_cost = "cost"
let api_privacy_policy = "privacy"
let api_countryid = "countryid"
let api_regionid  = "regionid"
let api_city      = "city"
let api_street    = "street"
let api_street2    = "street2"
let api_postcode  = "postcode"
let api_addressid  = "addressid"
let api_address_type  = "address_type"
let api_zip = "zip"
let api_search  = "search"
let api_storeid  = "storeid"
let api_store_id  = "store_id"
let api_latitude  = "latitude"
let api_longitude  = "longitude"
let api_category_id  = "categoryId"





let local_instagram = "instagram"
let local_twitter = "twitter"
let local_facebook = "facebook"
let local_snapchat = "snapchat"
let local_landing_image = "landingImage"
let local_loyalty_details = "loyalty_details"


//New
let api_reseller_id = "reseller_id"
let api_vendor_id = "vendor_id"

let api_pricelist_id = "pricelist_id"
let api_stage_id = "stage_id"

let api_state = "state"

let api_rec_name = "rec_name"

let api_enduser_id = "enduser_id"
let api_iLike = "ilike"

let api_login = "login"
let api_password = "password"
let api_old_password = "old_password"
let api_new_password = "new_password"
let api_model_name = "model_name"
let api_domain = "domain"

let api_category_name = "category_name"
let api_offset = "offset"
let api_limit = "limit"
let api_order = "order"
let api_name = "name"
let api_event_type = "event_type"
let api_type = "type"

let api_vals = "vals"
let api_vendors_ids = "vendors_ids"
let api_event_id = "event_id"
let api_partner_id = "partner_id"
let api_country_id = "country_id"
let api_mobile = "mobile"
let api_organization = "organization"
let api_job_title = "job_title"
let api_industry = "industry"
let api_no_of_employees = "no_of_employees"
let api_company_name = "company_name"
let api_job_position = "job_position"
let api_email_add = "email_add"
let api_phone_no = "phone_no"
let api_phone = "phone"
let api_msg = "msg"
let api_quote_id = "quote_id"
let api_first_preference = "first_preference"
let api_second_preference = "second_preference"
let api_first_timezone = "first_timezone"
let api_second_timezone = "second_timezone"
let api_vendors_request_ids = "vendors_request_ids"
let api_vendor_request_ids = "vendor_request_ids"
let api_reseller = "reseller"
let api_product_id = "product_id"
let api_product_uom_qty = "product_uom_qty"
let api_order_line = "order_line"
let api_end_user_company = "end_user_company"
let api_department = "department"
let api_designation = "designation"
let api_parent_id = "parent_id"
let api_record_id = "record_id"
let api_order_id = "order_id"
let api_partner_shipping_id = "partner_shipping_id"
let api_partner_invoice_id = "partner_invoice_id"
let api_change_payment_term = "change_payment_term"
let api_payment_term_id = "payment_term_id"
let api_opportunity_id = "opportunity_id"
let api_company_type = "company_type"
let api_state_id = "state_id"
let api_website = "website"
let api_contact = "contact"
let api_child_ids = "child_ids"
let api_order_country_id = "order_country_id"
let api_invoice_id = "invoice_id"
let api_invoice_url = "invoice_url"
let api_payment_state = "payment_state"
let api_invoice_origin = "invoice_origin"
let api_enduser_user_id = "enduser_user_id"
let api_reseller_parent_id = "reseller_parent_id"
let api_reseller_person_id = "reseller_person_id"
let api_reseller_company_id = "reseller_company_id"
let api_company_email = "company_email"
let api_status = "status"
let api_token = "token"
let api_designation_id = "designation_id"
let api_deal_type = "deal_type"
let api_field_name = "field_name"
let api_version = "version"
let api_deal_id = "deal_id"
let api_user_id = "user_id"
let api_is_end_user = "is_end_user"
let api_industry_id = "industry_id"
let api_deviceToken = "deviceToken"
let api_userId = "userId"
let api_rec_id = "rec_id"
let api_rating = "rating"
let api_reseller_company_ids = "reseller_company_ids"
let api_new_payment_term_id = "new_payment_term_id"
